# Generated by Django 4.1.3 on 2022-11-27 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blog', '0003_alter_hashtag_parent_hash_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='parent_hash_tag',
        ),
        migrations.AddField(
            model_name='hashtag',
            name='parent_hashtag_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_hashtags', to='simple_blog.hashtag'),
        ),
    ]
