# Generated by Django 4.1.3 on 2022-11-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simple_blog', '0004_remove_hashtag_parent_hash_tag_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='parent_hashtag_id',
            new_name='parent_hashtag',
        ),
    ]
